apiVersion: v1
kind: Service
metadata:
  name: dotnetdemo
  namespace: dotnet-space
spec:
  selector:
    app: dotnetdemo
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    ClientIP:
      timeoutSeconds: 10800
  ports:
    - name: dotnetdemo
      protocol: TCP
      port: 80
      targetPort: 5000