apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  namespace: newnamespace
  labels:
    app: dotnetdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: anveshreg.azurecr.io/dotnetdemo:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: bob